### ISSUE TITLE
got an issue when starting

### ISSUE THREAD

**Issue by DanteHsk** [HumanTree92/esx_advancedjail#1]
Error loading script server/main.lua in resource esx_advancedjail: @esx_advancedjail/server/main.lua:38: attempt to call a nil value (field 'RegisterCommand')
stack traceback:
	@esx_advancedjail/server/main.lua:38: in main chunk
Failed to load script server/main.lua.

this is the passage:

ESX.RegisterCommand('jail', 'mod', function(xPlayer, args, showError)
	TriggerEvent('esx_advancedjail:sendToJail', args.playerId, args.time * 60, 'bp1', false)
end, true, {help = 'Jail a Player', validate = true, arguments = {
	{name = 'playerId', help = 'Player Id', type = 'playerId'},
	{name = 'time', help = 'Jail Time in Minutes', type = 'number'}
}})

**Comment by HumanTree92** [comment]
Update ur FiveM. And update to the latest es_extended or latest exm

**Comment by CC3462** [comment]
Error loading script server/main.lua in resource esx_advancedjail: @esx_advancedjail/server/main.lua:38: attempt to call a nil value (field 'RegisterCommand')
stack traceback:
@esx_advancedjail/server/main.lua:38: in main chunk
Failed to load script server/main.lua.

What's in the script:

ESX.RegisterCommand('jail', 'mod', function(xPlayer, args, showError)
TriggerEvent('esx_advancedjail:sendToJail', args.playerId, args.time * 60, 'bp1', false)
end, true, {help = 'Jail a Player', validate = true, arguments = {
{name = 'playerId', help = 'Player Id', type = 'playerId'},
{name = 'time', help = 'Jail Time in Minutes', type = 'number'}
}}) 

I am using es_extended v1 final
