### ISSUE TITLE
Citizen interaction "Jail" not appearing

### ISSUE THREAD

**Issue by LimeSucker** [HumanTree92/esx_advancedjail#10]
**Describe the Bug | A Clear & Concise Description of Bug**
In the F6 menu, as a Police Officer, the option for "Jail" doesn't appear despite intalling everything. 
I changed the code in the esx_policejob/client/main as instructed

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2.0-final
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Windows

**Comment by HumanTree92** [comment]
There can't be an issue with this script. If the option for Jail isn't in your Menu then that is on your end not mine. You should make sure you follow https://github.com/HumanTree92/esx_advancedjail/blob/master/esx_policejob_add.lua#L4 as well as https://github.com/HumanTree92/esx_advancedjail/blob/master/locales/en.lua#L16
