### ISSUE TITLE
Jail removes inventory

### ISSUE THREAD

**Issue by Rasta-Sauce1** [HumanTree92/esx_advancedjail#11]
**Describe the Bug | A Clear & Concise Description of Bug**
I've set the config values to false for remove inventory but it is still clearing peoples inventory when jailed. not sure how to fix it as the function is calling the config.value and the config value is set to false. its also clearing loadouts i believe unless thats counted in the inventory for the script

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: no
Have you looked through the Closed Topics?: yes
Have you looked through the Wiki?: yes
Are you using a Pre-Installed ESX? If Yes who?: no
Are you using es_extended? If Yes what Version? (Example: 1.2): yes, 1.2
Are you using Essentialmode?: no
Are you using ExtendedMode?: no
Are you using OneSync?: yes
Linux or Windows?: windows

**Comment by HumanTree92** [comment]
This should now be fixed in https://github.com/HumanTree92/esx_advancedjail/commit/c12bdc3ce5ab736c29f5eb6bf897c43561f050bf

**Comment by Rasta-Sauce1** [comment]
thank you man. still around supporting you are a legend
