### ISSUE TITLE
SCRIPT ERROR: @esx_advancedjail/server/main.lua:8: attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by p4tric3** [HumanTree92/esx_advancedjail#5]
**Describe the Bug | A Clear & Concise Description of Bug**

So every time an user joines the server i get this error:

SCRIPT ERROR: @esx_advancedjail/server/main.lua:8: attempt to index a nil value (local 'xPlayer')
> cb (@es_extended/server/main.lua:215)
> ref (@es_extended/server/classes/player.lua:234)
>  (@mysql-async/mysql-async.js:14431)

And the script is working until i want to put someone in Jail

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: No
Are you using a Pre-Installed ESX? If Yes who?: Idk 
Are you using es_extended? If Yes what Version? (Example: 1.2):  1.1.0
Are you using Essentialmode?: Yes
Are you using ExtendedMode?:  Yes
Are you using OneSync?: No
Linux or Windows?: Linux (Ubuntu 18.04)

**Comment by HumanTree92** [comment]
If you would read the damn readme it states Required: es_extended V1 Final or extendedmode

Honestly you bug request makes no damn sense. For starters how TF do you not know if your using a preinstalled ESX & you are saying your using es_extended, Essentialmode, & ExtendedMode. Thats not even possible.

**Comment by p4tric3** [comment]
Sry, pls calm down, i'm not that known in fivem servers and esx etc. my bad :/
