### ISSUE TITLE
Issue with es_extended / Issue with other Jobs?

### ISSUE THREAD

**Issue by 0x01422** [HumanTree92/esx_advancedjail#8]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: n
Have you looked through the Closed Topics?: y
Have you looked through the Wiki?: y
Are you using a Pre-Installed ESX? If Yes who?: n
Are you using es_extended? If Yes what Version? (Example: 1.2): 1.2
Are you using Essentialmode?: n
Are you using ExtendedMode?: n
Are you using OneSync?: n
Linux or Windows?: w

Im using another job: fbi and i want to let fbi also arrest people. The issue with this is it's saying: 
![image](https://user-images.githubusercontent.com/59320846/105322628-6bcbbb00-5bc9-11eb-96a3-bcd680cd0698.png)

I made all changes correctfully and changed 
xPlayer.triggerEvent('esx_fbi_job:unrestrain')
and
if xPlayer.job.name == 'fbi'

**Comment by HumanTree92** [comment]
Did you do this https://github.com/HumanTree92/esx_advancedjail/blob/master/locales/en.lua#L16 ?

**Comment by 0x01422** [comment]
Yes I just did it. Now it says "jail" instead of having no translation. Still nothing happens when i press on it nor if im near a player. Nothing happens. No errors showing up

**Comment by Knox623** [comment]
> Yes I just did it. Now it says "jail" instead of having no translation. Still nothing happens when i press on it nor if im near a player. Nothing happens. No errors showing up

I'm having this exact issue too
