### ISSUE TITLE
Sending to different locations

### ISSUE THREAD

**Issue by JustMeGaming** [HumanTree92/esx_advancedjail#9]
**Describe the Bug | A Clear & Concise Description of Bug**

I see there are different areas for being locked up, how do I go about sending people to one or the other? Right now, /jail just sends people to prison.
**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?:  No
Have you looked through the Closed Topics?:  Yes
Have you looked through the Wiki?:  Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2):  1.2
Are you using Essentialmode?:  No.
Are you using ExtendedMode?: No.
Are you using OneSync?: Yes.
Linux or Windows?: Windows.

**Comment by HumanTree92** [comment]
/jail is meant to only jail at the prison. You need to follow https://github.com/HumanTree92/esx_advancedjail/blob/master/esx_policejob_add.lua to have multiple locations. /jail is meant for a staff thing.
